#!/usr/bin/env bash

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Homebrew, a good OS X package manager ..."
  ruby <(curl -fsSkL raw.github.com/mxcl/homebrew/go)
  brew update

echo "Installing the latest version of Git ..."
  brew install git

echo "Installing rbenv, a good ruby version manager ..."
  brew install rbenv

echo "Installing ruby-build, a simple way to build new ruby versions ..."
  brew install ruby-build

echo "Installing MySQL, a good open source relational database ..."
  brew install mysql

echo "Installing Redis, a good key-value database ..."
  brew install redis
